linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - asciicheck #
    - gocognit
    - godot
    - godox
    - goerr113
    - maligned
    - nestif
    - prealloc
    - testpackage
    - wsl

  # don't enable:
  # - gochecknoglobals
  # - gochecknoinits

issues:
  exclude-use-default: false
  max-same-issues: 0

